services:
    emhar_cqrs.synchronous_command_bus:
        class: Emhar\CqrsInfrastructureBundle\CommandBus\SymfonyEventDispatcherCommandBus
        public: true
        arguments: ['@event_dispatcher']
        tags:
            - { name: kernel.event_listener, event: 'cqrs-events-collected', method: 'dispatchPostedCommand' }
    emhar_cqrs.asynchronous_command_bus:
        class: Emhar\CqrsInfrastructureBundle\CommandBus\JmsJobQueueCommandBus
        public: true
        arguments: ['@doctrine']
        tags:
            - { name: kernel.event_listener, event: 'cqrs-events-collected', method: 'dispatchPostedCommand' }
    emhar_cqrs.doctrine_event_collector:
        class: Emhar\CqrsInfrastructureBundle\Event\DoctrineEventCollector
        public: false
        arguments: [[]] #see compiler pass, inject all repositories
        tags:
            - { name: doctrine.event_subscriber, connection: default }